name: Manual Broadcast

on:
  workflow_dispatch: # Додає кнопку ручного запуску

jobs:
  broadcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install firebase-admin requests

      - name: Run Broadcast Script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        run: python broadcast.py
